server:
  port: 8002
spring:
  application:
    name: EC-INVENTORY
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 8
      minimum-idle: 8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ec?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 111111

